# Generated by Django 4.2 on 2023-04-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_cont'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cont',
            new_name='Contact',
        ),
    ]
